POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username": "bob", "password": "Password123"}


###

POST http://127.0.0.1:8000/signup
Content-Type: application/json

{"username": "bob", "password": "Password123", "email": "bob@gmail.com"}

###

GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token 815056568aaff308c5373feb31fcc8a3e787b117

{}

