POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username": "bob", "password": "Password123"}


###

POST http://127.0.0.1:8000/signup
Content-Type: application/json

{"username": "bob", "password": "Password123", "email": "bob@gmail.com"}

###

GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token 35c5994e143d64586b5bd2f8fb4c628603b7a562

{}

