# Set-up Instructions
#
# Install REST Client extension for VS Code
# Run project backend sever (instructions found in README.md)
# Go to development server URL and add /admin
# Log in - user: admin pass: kmp000
# Test signup by sending HTTP request using REST Client
# Check Users tab under AUTHENTICATION AND AUTHORIZATION for successful signup
# Test login by sending a HTTP request using REST client
# Test token using token from Token tab under AUTH TOKEN and sending HTTP request using REST Client

# Request to login endpoint
POST http://127.0.0.1:8000/login
Content-Type: application/json

# Request body containing user credentials
{"email": "bob@gmail.com", "password": "Password123"}


###

# Request to signup endpoint
POST http://127.0.0.1:8000/signup
Content-Type: application/json

# Request body containing user registration details
{"username": "bob", "password": "Password123", "email": "bob@gmail.com"}

###

# Request to test_token endpoint
GET http://127.0.0.1:8000/test_token
Content-Type: application/json
# Authorization header containing user token
Authorization: Token d44dd15d9fe59a72ed203c3469ff355f8596e686

{}

